---
title: "R で学ぶゲーム理論"
author: "DS-SL"
date: "`r Sys.Date()`"
output:
  html_notebook:
    number_sections: yes
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---
> 表題の本の内容を学ぶためのファイル

# Setup

```{r eval=FALSE}
install.packages("remotes")
remotes::install_github("yukiyanai/rgamer")
```

```{r}
library(tidyverse)
library(rgamer)
```

必要なときに、実行

```{r eval=FALSE}
library(showtext)
showtext_auto()
```

```{r eval=FALSE}
theme_set(theme_gray(base_family = "HiraginoSans-W3"))
```

# R で体感するゲーム理論

```{r}
game1 <- normal_form(
  players = c("矢内", "上條"),
  s1 = c("表", "裏"),
  s2 = c("表", "裏"),
  payoffs1 = c(1,0,0,1),
  payoffs2 = c(0,1,1,0)
)
```

```{r}
s1_sol1 <- solve_nfg(game1)
```

```{r}
g1_sol2 <- solve_nfg(game1, mixed = TRUE)
g1_sol2$msNE
```

```{r}
g1_sol2$br_plot
```

```{r}
g1_sim <- sim_game(game1, 
                   n_samples = 100, 
                   n_periods = 50)
```

```{r}
a <- 25
sqrt(a)
```

# ゲームの定義と合理的なプレーヤー

```{r}
game2_1 <- normal_form(
  players = c("矢内", "上條"),
  s1 = c("表", "裏"),
  s2 = c("表", "裏"),
  payoffs1 = c(1,0,0,1),
  payoffs2 = c(0,1,1,0)
)
```

```{r}
g2_1_sol <- solve_nfg(game2_1)
```

```{r}
game2_2 <- normal_form(
  players = c("矢内", "上條"),
  s1 = c("グー", "チョキ", "パー"),
  s2 = c("グー", "チョキ", "パー"),
  payoffs1 = c(1,0,2,2,1,0,0,2,1),
  payoffs2 = c(0,2,0,0,1,2,2,0,1)
)
```

```{r}
g2_2_sol <- solve_nfg(game2_2)
```

# 支配戦略と支配される戦略の繰り返し消去

```{r}
game3_1 <- normal_form(
  players = c("矢内", "上條"),
  s1 = c("グー", "チョキ", "パー"),
  s2 = c("グー", "チョキ", "パー"),
  payoffs1 = c(0,0,2,2,0,0,0,2,2),
  payoffs2 = c(2,2,0,0,2,2,2,0,0)
)
```

```{r}
solve_nfg(game3_1, mark_br = FALSE)$table
```
オッズ

$$\frac{5/9}{4/9} = \frac{5}{4} = 1.25.$$

しかし、上條は、グーとパーだけ出せば良い。たとで、矢内が、グーと、チョキだけだしても結果は同じ。公平。

上條のチョキはパーに弱く支配されている。弱支配：weakly dominated.

```{r}
g3_1_dominated <- dom(game3_1)
```

1. 全部食べる 10
2. スイッチを押しに行く -1
3. 両方ともが食べる場合 大豚 8、子豚 2

```{r}
game3_2 <- normal_form(
  players = c("大豚", "子豚"),
  s1 = c("スイッチ", "待つ"),
  s2 = c("スイッチ", "待つ"),
  payoffs1 = c(7,10,4,0),
  payoffs2 = c(1,-1,5,0)
)

solve_nfg(game3_2, mark_br = FALSE)$table
```

```{r}
game3_2a <- eliminate_strategy(
  game3_2,
  player = "子豚",
  eliminated = "スイッチ"
)

solve_nfg(game3_2a, mark_br = FALSE)$table
```

```{r}
g3_2a_dominated <- dom(game3_2a)
```
```{r}
game3_2b <- eliminate_strategy(
  game3_2a,
  player = "大豚",
  eliminated = "待つ"
)

solve_nfg(game3_2b, mark_br = FALSE)$table
```

```{r}
g3_2b_dominated <- dom(game3_2b)
```
```{r}
g3_1_dominant <- dom(game3_1, type = "dominant")
g3_2_dominant <- dom(game3_2, type = "dominant")
```
## 練習問題

1. `game3_1` であいこは常に矢内が勝利するとするとどうなるか。関数 `dom()` を用いて分析せよ。

```{r}
game3_1x <- normal_form(
  players = c("矢内", "上條"),
  s1 = c("グー", "チョキ", "パー"),
  s2 = c("グー", "チョキ", "パー"),
  payoffs1 = c(0,0,2,2,0,0,0,2,0),
  payoffs2 = c(2,2,0,0,2,2,2,0,2)
)

solve_nfg(game3_1x, mark_br = FALSE)$table
```

```{r}
g3_1x_dominated <- dom(game3_1x)
```
```{r}
g3_1x_dominant <- dom(game3_1x, type = "dominant")
```

2. `game3_2` で、大豚がスイッチをオスには、-5 とする。このとき、大豚と、子豚は何を選択するか。

```{r}
game3_2x <- normal_form(
  players = c("大豚", "子豚"),
  s1 = c("スイッチ", "待つ"),
  s2 = c("スイッチ", "待つ"),
  payoffs1 = c(3,10,0,0),
  payoffs2 = c(1,-1,-1,0)
)

solve_nfg(game3_2x, mark_br = FALSE)$table
```

```{r}
g3_2x_dominated <- dom(game3_2x)
```
```{r}
g3_2x_dominant <- dom(game3_2x, type = "dominant")
```

# 参考文献

* 私たちのR: https://www.jaysong.net/RBook/
