---
title: "Mongolia and Japan"
author: "DS-SL"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  html_notebook: null
---
> We study data on Mongolia and Japan.

# Setup

```{r setup}
Sys.setenv(LANG = "en")
library(tidyverse)
library(WDI)
```

# Education

## Education in Japan

```{r cash = TRUE}
url_edu1 <- "https://www.gender.go.jp/about_danjo/whitepaper/r03/zentai/html/honpen/csv/zuhyo01-05-01.csv"
download.file(url_edu1, destfile = "data/edu1.csv")
guess_encoding("data/edu1.csv")
```

```{r}
df_edu1 <- read_csv("data/edu1.csv", locale = locale(encoding = "Shift-JIS"), skip = 2)
df_edu1
```

```{r}
colnames(df_edu1)
df_edu1$年度
```

```{r}
df_edu0 <- df_edu1
colnames(df_edu0) <- c("year", "highschool_m", "highschool_f", "vocational_m", "vocational_f", "university_m", "university_f", "juniorcol_f", "gradschool_m", "gradschool_f")
df_edu00 <- df_edu0 %>% mutate(year = 1950:2020, 
                   highschool = (highschool_m + highschool_f)/2,
                   vocational = (vocational_m + vocational_f)/2,
                   university = (university_m + university_f)/2, 
                   juniorcol = juniorcol_f,
                   gradschool = (gradschool_m + gradschool_f)/2) 
```

```{r}
df_edu00 %>% select(-(2:10)) %>%
  pivot_longer(!year, names_to = "schools", values_to = "percentage") %>%
  ggplot(aes(x = year, y = percentage, color = schools)) +
  geom_line()
```
```{r}
df_edu11 <- df_edu1 %>% mutate(年 = 1950:2020, 
                   高等学校 = (`高等学校等（男子）`+ `高等学校等（女子）`)/2,
                   専修学校 = (`専修学校（専門課程，男子）`+ `専修学校（専門課程，女子）`)/2,
                   大学 = (`大学（学部，男子）` + `大学（学部，女子）`)/2, 
                   短期大学 = `短期大学（本科，女子）`,
                   大学院 = (`大学院（男子）` + `大学院（女子）`)/2) %>%
  select(-(1:10))
df_edu11
```
```
df_edu11 %>% 
  pivot_longer(2:6, names_to = "学校", values_to = "進学率") %>%
  ggplot(aes(x = 年, y = 進学率, color = 学校)) +
  geom_line()
```

```{r}
df_edu11 %>% 
  pivot_longer(2:6, names_to = "学校", values_to = "進学率") %>%
  ggplot(aes(x = 年, y = 進学率, color = 学校)) +
  geom_line() +
  theme_gray (base_family = "HiraginoSans-W3") # or base_family = "HiraKakuPro-W3"
```


```{r}
df_edu1 %>% mutate(year = 1950:2020) %>%
  pivot_longer(2:10, names_to = "学校", values_to = "進学率") %>%
  ggplot(aes(x = year, y = 進学率, color = 学校)) +
  geom_line() +
  theme_gray (base_family = "HiraKakuPro-W3") # or base_family = "HiraginoSans-W3"
```
```#{r dev='rag_png'}
df_edu1 %>% mutate(year = 1950:2020) %>%
  pivot_longer(2:10, names_to = "学校", values_to = "進学率") %>%
  ggplot(aes(x = year, y = 進学率, color = 学校)) +
  geom_line()
```

```{=html}
<iframe src="https://data.worldbank.org/share/widget?indicators=SP.DYN.LE00.IN&locations=MN-JP-1W" width='450' height='300' frameBorder='0' scrolling="no" ></iframe>
```
